steps:

 
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'env.example', '.env']
  
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args: ["./gen-passwords.sh"]

- name: 'bash'
  args: ['echo', 'Starting docker compose up...'] 

- name: 'docker/compose:1.19.0'
  args: ['up', '--build', '-d']
  timeout: 500s
  
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'jitsi/jvb:latest', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']



- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'jitsi/web:latest', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']
 
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']



- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'jitsi/jicofo:latest', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']

- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'jitsi/prosody:latest', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']
  
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']
  
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'instance-groups', 'managed', 'rolling-action', 'restart', 'instance-group-1', '--zone=us-central1-a' ]

  
  
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['build', '-t', 'gcr.io/zaanu-82b5a/jvb','-f','./jvb/','.']
  
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['push', 'gcr.io/zaanu-82b5a/jvb']  
  
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['build', '-t', 'gcr.io/zaanu-82b5a/jicofo', '.']
  
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['push', 'gcr.io/zaanu-82b5a/jicofo']  
  
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['build', '-t', 'gcr.io/zaanu-82b5a/prosody', '.']
  
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['push', 'gcr.io/zaanu-82b5a/prosody']  

# - name: 'gcr.io/cloud-builders/docker'
#   args: ['build', '-t', 'gcr.io/zaanu-82b5a/web','-f','/web', '.']
  
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['push', 'gcr.io/zaanu-82b5a/web']  
