steps:

 
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'env.example', '.env']
  
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args: ["./gen-passwords.sh"]


# - name: 'bash'
#   args: ["./gen-passwords.sh"]

- name: 'bash'
  args: ['echo', 'Starting docker compose up...'] 

# - name: 'docker/compose:1.19.0'
#   args: ['build']
  
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/zaanu-82b5a/jitsi/jvb:stable-5870', '.']
  
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/zaanu-82b5a/jitsi/jvb:stable-5870']  
  
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/zaanu-82b5a/jitsi/jicofo:stable-5870', '.']
  
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/PROJECT_ID/jitsi/jicofo:stable-5870']  
  
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/zaanu-82b5a/jitsi/prosody:stable-5870', '.']
  
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/PROJECT_ID/jitsi/prosody:stable-5870']  

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/zaanu-82b5a/jitsi/web:stable-5870', '.']
  
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/PROJECT_ID/jitsi/web:stable-5870']  
